# Generated by Django 3.2.4 on 2021-06-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Isbn')),
                ('nombre_del_libro', models.CharField(max_length=20, verbose_name='Nombre del Libro')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Libros',
        ),
    ]
